*Work;
	*libname music "C:\Users\mmarti24\Dropbox\Papers\Cultural Tectonics\Data"; run;

*Home;
	libname music "C:\Users\matthew\Dropbox\Papers\Cultural Tectonics\Data"; run;

*Import Major 4;


  data MUSIC.MAJORS    ;
%let _EFIERR_ = 0; /* set the ERROR detection macro variable */
 infile 'C:\Users\matthew\Dropbox\Papers\Cultural Tectonics\Major 4.csv' delimiter =
',' MISSOVER DSD lrecl=32767 firstobs=2 ;
         informat Labels_Change $80. ;
         informat Labels $80. ;
         informat Note $80. ;
         informat Distribution $80. ;
         informat Independent_Status best32. ;
         informat Level $2. ;
         informat Y1989 $30. ;
         informat Y1990 $30. ;
         informat Y1991 $30. ;
         informat Y1992 $30. ;
         informat Y1993 $30. ;
         informat Y1994 $30. ;
         informat Y1995 $30. ;
         informat Y1996 $30. ;
         informat Y1997 $30. ;
         informat Y1998 $30. ;
         informat Y1999 $30. ;
         informat Y2000 $30. ;
         informat Y2001 $30. ;
         informat Y2002 $30. ;
         informat Y2003 $30. ;
         informat Y2004 $30. ;
         informat Y2005 $30. ;
         informat Y2006 $30. ;
         informat Y2007 $30. ;
         informat Y2008 $30. ;
         informat Y2009 $30. ;
         informat Y2010 $30. ;
         informat Y2011 $30. ;
         informat Y2012 $30. ;
         informat Y2013 $30. ;
         informat Y2014 $30. ;
         informat Y2015 $30. ;
         format Labels_Change $80. ;
         format Labels $80. ;
         format Note $80. ;
         format Distribution $80. ;
         format Independent_Status best12. ;
         format Level $2. ;
         format Y1989 $30. ;
         format Y1990 $30. ;
         format Y1991 $30. ;
         format Y1992 $30. ;
         format Y1993 $30. ;
         format Y1994 $30. ;
         format Y1995 $30. ;
         format Y1996 $30. ;
         format Y1997 $30. ;
         format Y1998 $30. ;
         format Y1999 $30. ;
         format Y2000 $30. ;
         format Y2001 $30. ;
         format Y2002 $30. ;
         format Y2003 $30. ;
         format Y2004 $30. ;
         format Y2005 $30. ;
         format Y2006 $30. ;
         format Y2007 $30. ;
         format Y2008 $30. ;
         format Y2009 $30. ;
         format Y2010 $30. ;
         format Y2011 $30. ;
         format Y2012 $30. ;
         format Y2013 $30. ;
         format Y2014 $30. ;
         format Y2015 $30. ;
      input
                  Labels_Change $
                  Labels $
                  Note $
                  Distribution $
                  Independent_Status
                  Level $
                  Y1989 $
                  Y1990 $
                  Y1991 $
                  Y1992 $
                  Y1993 $
                  Y1994 $
                  Y1995 $
                  Y1996 $
                  Y1997 $
                  Y1998 $
                  Y1999 $
                  Y2000 $
                  Y2001 $
                  Y2002 $
                  Y2003 $
                  Y2004 $
                  Y2005 $
                  Y2006 $
                  Y2007 $
                  Y2008 $
                  Y2009 $
                  Y2010 $
                  Y2011 $
                  Y2012 $
                  Y2013 $
                  Y2014 $
                  Y2015 $
      ;
      if _ERROR_ then call symputx('_EFIERR_',1);  /* set ERROR detection macro variable */
      run;

*Merge All Data;
proc sort data=music.final_completesongs; by songid;
data uniquesongs; set music.final_uniquesongs;
keep songid weekson;
run;
proc sort data=uniquesongs; by songid;
run;
data songs; merge music.final_completesongs uniquesongs; by songid;
run;

data songs; set songs;
label1a=label1;
If label1= 'Arista' then label1a= 'Arista Records';
If label1= 'Atlantic' then label1a= 'Atlantic Records';
If label1= 'Atlantic Recording Corporation' then label1a= 'Atlantic Records';
If label1= 'Bad Boy Entertainment' then label1a= 'Bad Boy Records';
If label1= 'Blunt Recordings' then label1a= 'Blunt Records';
If label1= 'Capitol Records, LLC' then label1a= 'Capitol Records';
If label1= 'Columbia' then label1a= 'Columbia Records';
If label1= 'Def Jam Recordings Group Inc.' then label1a= 'Def Jam Recordings';
If label1= 'Def Jam Music Group' then label1a= 'Def Jam Recordings';
If label1= 'EastWest Records America' then label1a= 'EastWest';
If label1= 'EastWest Recrods America' then label1a= 'EastWest';
If label1= 'Elektra' then label1a= 'Elektra Records';
If label1= 'G.O.O.D. MUSIC' then label1a= 'G.O.O.D Music';
If label1= 'How You Love That' then label1a= 'How You Love That Records';
If label1= 'Island Black Music' then label1a= 'Island';
If label1= 'Island Records' then label1a= 'Island';
If label1= 'Island Records Group' then label1a= 'Island';
If label1= 'Penalty Recordings' then label1a= 'Penalty Records';
If label1= 'PWL America Records Ltd.' then label1a= 'PWL America Records Ltd';
If label1= 'RCA' then label1a= 'RCA Records';
If label1= 'Roc Nation LLC' then label1a= 'Roc Nation';
If label1= 'Rostrum Recrods' then label1a= 'Rostrum Records';
If label1= 'Star Trek Entertainment' then label1a= 'Star Trak Entertainment';
If label1= 'Universal Motown' then label1a= 'Motown';
If label1= 'Universal Motown Records' then label1a= 'Motown';
If label1= 'Universal Motwon' then label1a= 'Motown';
If label1= 'Universal Republic' then label1a= 'Republic Records';
If label1= 'Universal Records' then label1a= 'Universal';
If label1= 'Universal Recrods' then label1a= 'Universal';
If label1= 'Universal Music' then label1a= 'Universal';
If label1= 'Universal Music B.V.' then label1a= 'Universal';
If label1= 'Universal Music Operations Ltd.' then label1a= 'Universal';
If label1= 'Virgin Records America, Inc.' then label1a= 'Virgin';
If label1= 'Virgin Records Ltd.' then label1a= 'Virgin';
If label1= 'Virgin America' then label1a= 'Virgin';
If label1= 'VP Recrods' then label1a= 'VP Records';
If label1= 'Warlock Reocrds' then label1a= 'Warlock Records';
If label1= 'Sup Pup' then label1a= 'Sup Pop';
If label1= 'A1' then label1a= 'A1 Recordings';
If label1= 'BMG Eurodisc' then label1a= 'Arista Records';
If (label1= 'WARNER Music Benelux' & NewArtist='Macklemore') then label1a= 'Macklemore, LLC';
If (label1= 'WARNER Music Benelux' & NewArtist='Bob') then label1a= 'Atlantic Records';
If (label1= 'Warner Dance Labels' & NewArtist='Bob') then label1a= 'Atlantic Records';
If (label1= 'Warner Dance Labels' & NewArtist='Flo rida') then label1a= 'Atlantic Records';	
If label1= 'Terror Squad' then label1a= 'Terror Squad Entertainment';
If label1= 'Terror Squad Production' then label1a= 'Terror Squad Entertainment';
If label1= 'Bertelsmann Music Group' then label1a= 'BMG';
If label1= 'Big Life' then label1a= 'Tommy Boy';
If label1= 'Big Yard Music Group Ltd.' then label1a= 'MCA Records';
If label1= 'Bilawn Records' then label1a= 'Rhyme $yndicate Records';
If label1= 'Brainstorm Entertainment' then label1a= 'Brainstorm Enterprise';
If label1= 'Bystorm Entertainment' then label1a= 'Universal';
If label1= 'Violator' then label1a= 'Violator Records';
If label1= 'TVT Europe' then label1a= 'TVT Records';
If label1= 'Top Dawg' then label1a= 'Top Dawg Entertainment';
If label1= 'Thugged Out Entertainment' then label1a= 'Thugged Out Militainment';
If label1= 'Cheetah Recrods' then label1a= 'Cheetah Records';
If label1= 'CMG' then label1a= 'So So Def';
If label1= 'Col' then label1a= 'Cold Chillin';
If label1= 'ColliPark Music' then label1a= 'Collipark Records';
If label1= 'Deh Tyme Entertainment, Inc.' then label1a= 'Deh Tyme Entertainment';
If label1= 'Def Jam Classics' then label1a= 'Def Jam Recordings';
If label1= 'X-Mix' then label1a= 'Island Def Jam Music Group';
If label1= 'UNDEAS Recordings' then label1a= 'Undeas Recording';
If label1= 'Ultimix' then label1a= 'Violator Records';
If label1= 'Maybach Music' then label1a= 'Maybach Music Group';
If label1= 'Mega Records' then label1a= 'Tommy Boy';
If label1= 'Soundtable' then label1a= 'Giant Records';
If label1= 'Stampa Alternativa' then label1a= 'Chrysalis';
If label1= 'Sick Wild’ It Records' then label1a= 'Sick Wid It Records';
If label1= 'SBK' then label1a= 'SBK Records';
If label1= 'Noiseland' then label1a= 'Macklemore, LLC';
If label1= 'Northwestide Records' then label1a= 'Roc-A-Fella Records';
If label1= "October's Very Own" then label1a= 'Young Money Entertainment';
If label1= 'P.R.O. Division' then label1a= 'Rush Associated Labels';
If label1= 'Paisley Park' then label1a= 'Warner Bros. Records';
If label1= 'Warner Bros' then label1a= 'Warner Bros. Records';
If label1= 'Hustle' then label1a= 'Grand Hustle';
If label1= 'Hustle Entertainment' then label1a= 'Grand Hustle';
If label1= 'Hustle Gang' then label1a= 'Grand Hustle';
If label1= 'Studio 2000' then label1a= 'VP Records';
If label1= 'Skywalker Records' then label1a= 'Luke Records';
If label1= 'Skyywalker Records' then label1a= 'Luke Records';
If label1= 'Luke Skywalker Records' then label1a= 'Luke Records';
If label1= 'Getting Out Our Dreams' then label1a= 'G.O.O.D Music';
If label1= 'GMG' then label1a= 'Get Money Gang Entertainment';
If label1= 'Polystar (3)' then label1a= 'Island Def Jam Music Group';
If label1= 'Mergela Records' then label1a= 'Interscope Records';
If label1= 'Mighty Mouse' then label1a= 'Mighty Music';
If label1= 'Monami Entertainment' then label1a= 'Atlantic Records';
If label1= 'ISBA' then label1a= 'Tommy Boy';
If label1= 'Konlive' then label1a= 'Geffen Records';
If label1= 'Lexington' then label1a= 'Rush Associated Labels';
If label1= 'JSRC' then label1a= 'Diamond Style Records';
If label1= 'Poe Boy Music' then label1a= 'Poe Boy Entertainment';
If label1= "Cold Chillin'" then label1a= "Cold Chillin";
If label1= 'La Face Records' then label1a= 'LaFace Records';
If (year=1998 & label1a= 'PWL America Records Ltd') then label1a='RCA Records';

label2a=label2;
If label2= 'Arista' then label2a= 'Arista Records';
If label2= 'Atlantic' then label2a= 'Atlantic Records';
If label2= 'Atlantic Recording Corporation' then label2a= 'Atlantic Records';
If label2= 'Bad Boy Entertainment' then label2a= 'Bad Boy Records';
If label2= 'Blunt Recordings' then label2a= 'Blunt Records';
If label2= 'Capitol Records, LLC' then label2a= 'Capitol Records';
If label2= 'Columbia' then label2a= 'Columbia Records';
If label2= 'Def Jam Recordings Group Inc.' then label2a= 'Def Jam Recordings';
If label2= 'Def Jam Music Group' then label2a= 'Def Jam Recordings';
If label2= 'EastWest Records America' then label2a= 'EastWest';
If label2= 'EastWest Recrods America' then label2a= 'EastWest';
If label2= 'Elektra' then label2a= 'Elektra Records';
If label2= 'G.O.O.D. MUSIC' then label2a= 'G.O.O.D Music';
If label2= 'How You Love That' then label2a= 'How You Love That Records';
If label2= 'Island Black Music' then label2a= 'Island';
If label2= 'Island Records' then label2a= 'Island';
If label2= 'Island Records Group' then label2a= 'Island';
If label2= 'Penalty Recordings' then label2a= 'Penalty Records';
If label2= 'PWL America Records Ltd.' then label2a= 'PWL America Records Ltd';
If label2= 'RCA' then label2a= 'RCA Records';
If label2= 'Roc Nation LLC' then label2a= 'Roc Nation';
If label2= 'Rostrum Recrods' then label2a= 'Rostrum Records';
If label2= 'Star Trek Entertainment' then label2a= 'Star Trak Entertainment';
If label2= 'Universal Motown' then label2a= 'Motown';
If label2= 'Universal Motown Records' then label2a= 'Motown';
If label2= 'Universal Motwon' then label2a= 'Motown';
If label2= 'Universal Republic' then label2a= 'Republic Records';
If label2= 'Universal Records' then label2a= 'Universal';
If label2= 'Universal Recrods' then label2a= 'Universal';
If label2= 'Universal Music' then label2a= 'Universal';
If label2= 'Universal Music B.V.' then label2a= 'Universal';
If label2= 'Universal Music Operations Ltd.' then label2a= 'Universal';
If label2= 'Virgin Records America, Inc.' then label2a= 'Virgin';
If label2= 'Virgin Records Ltd.' then label2a= 'Virgin';
If label2= 'Virgin America' then label2a= 'Virgin';
If label2= 'VP Recrods' then label2a= 'VP Records';
If label2= 'Warlock Reocrds' then label2a= 'Warlock Records';
If label2= 'Sup Pup' then label2a= 'Sup Pop';
If label2= 'A1' then label2a= 'A1 Recordings';
If label2= 'BMG Eurodisc' then label2a= 'Arista Records';
If (label2= 'WARNER Music Benelux' & NewArtist='Macklemore') then label2a= 'Macklemore, LLC';
If (label2= 'WARNER Music Benelux' & NewArtist='Bob') then label2a= 'Atlantic Records';	
If (label2= 'Warner Dance Labels' & NewArtist='Bob') then label2a= 'Atlantic Records';	
If (label2= 'Warner Dance Labels' & NewArtist='Flo rida') then label2a= 'Atlantic Records';	
If label2= 'Terror Squad' then label2a= 'Terror Squad Entertainment';
If label2= 'Terror Squad Production' then label2a= 'Terror Squad Entertainment';
If label2= 'Bertelsmann Music Group' then label2a= 'BMG';
If label2= 'Big Life' then label2a= 'Tommy Boy';
If label2= 'Big Yard Music Group Ltd.' then label2a= 'MCA Records';
If label2= 'Bilawn Records' then label2a= 'Rhyme $yndicate Records';
If label2= 'Brainstorm Entertainment' then label2a= 'Brainstorm Enterprise';
If label2= 'Bystorm Entertainment' then label2a= 'Universal';
If label2= 'Violator' then label2a= 'Violator Records';
If label2= 'TVT Europe' then label2a= 'TVT Records';
If label2= 'Top Dawg' then label2a= 'Top Dawg Entertainment';
If label2= 'Thugged Out Entertainment' then label2a= 'Thugged Out Militainment';
If label2= 'Cheetah Recrods' then label2a= 'Cheetah Records';
If label2= 'CMG' then label2a= 'So So Def';
If label2= 'Col' then label2a= 'Cold Chillin';
If label2= 'ColliPark Music' then label2a= 'Collipark Records';
If label2= 'Deh Tyme Entertainment, Inc.' then label2a= 'Deh Tyme Entertainment';
If label2= 'Def Jam Classics' then label2a= 'Def Jam Recordings';
If label2= 'X-Mix' then label2a= 'Island Def Jam Music Group';
If label2= 'UNDEAS Recordings' then label2a= 'Undeas Recording';
If label2= 'Ultimix' then label2a= 'Violator Records';
If label2= 'Maybach Music' then label2a= 'Maybach Music Group';
If label2= 'Mega Records' then label2a= 'Tommy Boy';
If label2= 'Soundtable' then label2a= 'Giant Records';
If label2= 'Stampa Alternativa' then label2a= 'Chrysalis';
If label2= 'Sick Wild’ It Records' then label2a= 'Sick Wid It Records';
If label2= 'SBK' then label2a= 'SBK Records';
If label2= 'Noiseland' then label2a= 'Macklemore, LLC';
If label2= 'Northwestide Records' then label2a= 'Roc-A-Fella Records';
If label2= "October's Very Own" then label2a= 'Young Money Entertainment';
If label2= 'P.R.O. Division' then label2a= 'Rush Associated Labels';
If label2= 'Paisley Park' then label2a= 'Warner Bros. Records';
If label2= 'Warner Bros' then label2a= 'Warner Bros. Records';
If label2= 'Hustle' then label2a= 'Grand Hustle';
If label2= 'Hustle Entertainment' then label2a= 'Grand Hustle';
If label2= 'Hustle Gang' then label2a= 'Grand Hustle';
If label2= 'Studio 2000' then label2a= 'VP Records';
If label2= 'Skywalker Records' then label2a= 'Luke Records';
If label2= 'Skyywalker Records' then label2a= 'Luke Records';
If label2= 'Luke Skywalker Records' then label2a= 'Luke Records';
If label2= 'Getting Out Our Dreams' then label2a= 'G.O.O.D Music';
If label2= 'GMG' then label2a= 'Get Money Gang Entertainment';
If label2= 'Polystar (3)' then label2a= 'Island Def Jam Music Group';
If label2= 'Mergela Records' then label2a= 'Interscope Records';
If label2= 'Mighty Mouse' then label2a= 'Mighty Music';
If label2= 'Monami Entertainment' then label2a= 'Atlantic Records';
If label2= 'ISBA' then label2a= 'Tommy Boy';
If label2= 'Konlive' then label2a= 'Geffen Records';
If label2= 'Lexington' then label2a= 'Rush Associated Labels';
If label2= 'JSRC' then label2a= 'Diamond Style Records';
If label2= 'Poe Boy Music' then label2a= 'Poe Boy Entertainment';
If label2= "Cold Chillin'" then label2a= "Cold Chillin";
If label2= 'La Face Records' then label2a= 'LaFace Records';

label3a=label3;
If label3= 'Arista' then label3a= 'Arista Records';
If label3= 'Atlantic' then label3a= 'Atlantic Records';
If label3= 'Atlantic Recording Corporation' then label3a= 'Atlantic Records';
If label3= 'Bad Boy Entertainment' then label3a= 'Bad Boy Records';
If label3= 'Blunt Recordings' then label3a= 'Blunt Records';
If label3= 'Capitol Records, LLC' then label3a= 'Capitol Records';
If label3= 'Columbia' then label3a= 'Columbia Records';
If label3= 'Def Jam Recordings Group Inc.' then label3a= 'Def Jam Recordings';
If label3= 'Def Jam Music Group' then label3a= 'Def Jam Recordings';
If label3= 'EastWest Records America' then label3a= 'EastWest';
If label3= 'EastWest Recrods America' then label3a= 'EastWest';
If label3= 'Elektra' then label3a= 'Elektra Records';
If label3= 'G.O.O.D. MUSIC' then label3a= 'G.O.O.D Music';
If label3= 'How You Love That' then label3a= 'How You Love That Records';
If label3= 'Island Black Music' then label3a= 'Island';
If label3= 'Island Records' then label3a= 'Island';
If label3= 'Island Records Group' then label3a= 'Island';
If label3= 'Penalty Recordings' then label3a= 'Penalty Records';
If label3= 'PWL America Records Ltd.' then label3a= 'PWL America Records Ltd';
If label3= 'RCA' then label3a= 'RCA Records';
If label3= 'Roc Nation LLC' then label3a= 'Roc Nation';
If label3= 'Rostrum Recrods' then label3a= 'Rostrum Records';
If label3= 'Star Trek Entertainment' then label3a= 'Star Trak Entertainment';
If label3= 'Universal Motown' then label3a= 'Motown';
If label3= 'Universal Motown Records' then label3a= 'Motown';
If label3= 'Universal Motwon' then label3a= 'Motown';
If label3= 'Universal Republic' then label3a= 'Republic Records';
If label3= 'Universal Records' then label3a= 'Universal';
If label3= 'Universal Recrods' then label3a= 'Universal';
If label3= 'Universal Music' then label3a= 'Universal';
If label3= 'Universal Music B.V.' then label3a= 'Universal';
If label3= 'Universal Music Operations Ltd.' then label3a= 'Universal';
If label3= 'Virgin Records America, Inc.' then label3a= 'Virgin';
If label3= 'Virgin Records Ltd.' then label3a= 'Virgin';
If label3= 'Virgin America' then label3a= 'Virgin';
If label3= 'VP Recrods' then label3a= 'VP Records';
If label3= 'Warlock Reocrds' then label3a= 'Warlock Records';
If label3= 'Sup Pup' then label3a= 'Sup Pop';
If label3= 'A1' then label3a= 'A1 Recordings';
If label3= 'BMG Eurodisc' then label3a= 'Arista Records';
If (label3= 'WARNER Music Benelux' & NewArtist='Macklemore') then label3a= 'Macklemore, LLC';
If (label3= 'WARNER Music Benelux' & NewArtist='Bob') then label3a= 'Atlantic Records';	
If (label3= 'Warner Dance Labels' & NewArtist='Bob') then label3a= 'Atlantic Records';	
If (label3= 'Warner Dance Labels' & NewArtist='Flo rida') then label3a= 'Atlantic Records';		
If label3= 'Terror Squad' then label3a= 'Terror Squad Entertainment';
If label3= 'Terror Squad Production' then label3a= 'Terror Squad Entertainment';
If label3= 'Bertelsmann Music Group' then label3a= 'BMG';
If label3= 'Big Life' then label3a= 'Tommy Boy';
If label3= 'Big Yard Music Group Ltd.' then label3a= 'MCA Records';
If label3= 'Bilawn Records' then label3a= 'Rhyme $yndicate Records';
If label3= 'Brainstorm Entertainment' then label3a= 'Brainstorm Enterprise';
If label3= 'Bystorm Entertainment' then label3a= 'Universal';
If label3= 'Violator' then label3a= 'Violator Records';
If label3= 'TVT Europe' then label3a= 'TVT Records';
If label3= 'Top Dawg' then label3a= 'Top Dawg Entertainment';
If label3= 'Thugged Out Entertainment' then label3a= 'Thugged Out Militainment';
If label3= 'Cheetah Recrods' then label3a= 'Cheetah Records';
If label3= 'CMG' then label3a= 'So So Def';
If label3= 'Col' then label3a= 'Cold Chillin';
If label3= 'ColliPark Music' then label3a= 'Collipark Records';
If label3= 'Deh Tyme Entertainment, Inc.' then label3a= 'Deh Tyme Entertainment';
If label3= 'Def Jam Classics' then label3a= 'Def Jam Recordings';
If label3= 'X-Mix' then label3a= 'Island Def Jam Music Group';
If label3= 'UNDEAS Recordings' then label3a= 'Undeas Recording';
If label3= 'Ultimix' then label3a= 'Violator Records';
If label3= 'Maybach Music' then label3a= 'Maybach Music Group';
If label3= 'Mega Records' then label3a= 'Tommy Boy';
If label3= 'Soundtable' then label3a= 'Giant Records';
If label3= 'Stampa Alternativa' then label3a= 'Chrysalis';
If label3= 'Sick Wild’ It Records' then label3a= 'Sick Wid It Records';
If label3= 'SBK' then label3a= 'SBK Records';
If label3= 'Noiseland' then label3a= 'Macklemore, LLC';
If label3= 'Northwestide Records' then label3a= 'Roc-A-Fella Records';
If label3= "October's Very Own" then label3a= 'Young Money Entertainment';
If label3= 'P.R.O. Division' then label3a= 'Rush Associated Labels';
If label3= 'Paisley Park' then label3a= 'Warner Bros. Records';
If label3= 'Warner Bros' then label3a= 'Warner Bros. Records';
If label3= 'Hustle' then label3a= 'Grand Hustle';
If label3= 'Hustle Entertainment' then label3a= 'Grand Hustle';
If label3= 'Hustle Gang' then label3a= 'Grand Hustle';
If label3= 'Studio 2000' then label3a= 'VP Records';
If label3= 'Skywalker Records' then label3a= 'Luke Records';
If label3= 'Skyywalker Records' then label3a= 'Luke Records';
If label3= 'Luke Skywalker Records' then label3a= 'Luke Records';
If label3= 'Getting Out Our Dreams' then label3a= 'G.O.O.D Music';
If label3= 'GMG' then label3a= 'Get Money Gang Entertainment';
If label3= 'Polystar (3)' then label3a= 'Island Def Jam Music Group';
If label3= 'Mergela Records' then label3a= 'Interscope Records';
If label3= 'Mighty Mouse' then label3a= 'Mighty Music';
If label3= 'Monami Entertainment' then label3a= 'Atlantic Records';
If label3= 'ISBA' then label3a= 'Tommy Boy';
If label3= 'Konlive' then label3a= 'Geffen Records';
If label3= 'Lexington' then label3a= 'Rush Associated Labels';
If label3= 'JSRC' then label3a= 'Diamond Style Records';
If label3= 'Poe Boy Music' then label3a= 'Poe Boy Entertainment';
If label3= "Cold Chillin'" then label3a= "Cold Chillin";
If label3= 'La Face Records' then label3a= 'LaFace Records';

label4a=label4;
If label4= 'Arista' then label4a= 'Arista Records';
If label4= 'Atlantic' then label4a= 'Atlantic Records';
If label4= 'Atlantic Recording Corporation' then label4a= 'Atlantic Records';
If label4= 'Bad Boy Entertainment' then label4a= 'Bad Boy Records';
If label4= 'Blunt Recordings' then label4a= 'Blunt Records';
If label4= 'Capitol Records, LLC' then label4a= 'Capitol Records';
If label4= 'Columbia' then label4a= 'Columbia Records';
If label4= 'Def Jam Recordings Group Inc.' then label4a= 'Def Jam Recordings';
If label4= 'Def Jam Music Group' then label4a= 'Def Jam Recordings';
If label4= 'EastWest Records America' then label4a= 'EastWest';
If label4= 'EastWest Recrods America' then label4a= 'EastWest';
If label4= 'Elektra' then label4a= 'Elektra Records';
If label4= 'G.O.O.D. MUSIC' then label4a= 'G.O.O.D Music';
If label4= 'How You Love That' then label4a= 'How You Love That Records';
If label4= 'Island Black Music' then label4a= 'Island';
If label4= 'Island Records' then label4a= 'Island';
If label4= 'Island Records Group' then label4a= 'Island';
If label4= 'Penalty Recordings' then label4a= 'Penalty Records';
If label4= 'PWL America Records Ltd.' then label4a= 'PWL America Records Ltd';
If label4= 'RCA' then label4a= 'RCA Records';
If label4= 'Roc Nation LLC' then label4a= 'Roc Nation';
If label4= 'Rostrum Recrods' then label4a= 'Rostrum Records';
If label4= 'Star Trek Entertainment' then label4a= 'Star Trak Entertainment';
If label4= 'Universal Motown' then label4a= 'Motown';
If label4= 'Universal Motown Records' then label4a= 'Motown';
If label4= 'Universal Motwon' then label4a= 'Motown';
If label4= 'Universal Republic' then label4a= 'Republic Records';
If label4= 'Universal Records' then label4a= 'Universal';
If label4= 'Universal Recrods' then label4a= 'Universal';
If label4= 'Universal Music' then label4a= 'Universal';
If label4= 'Universal Music B.V.' then label4a= 'Universal';
If label4= 'Universal Music Operations Ltd.' then label4a= 'Universal';
If label4= 'Virgin Records America, Inc.' then label4a= 'Virgin';
If label4= 'Virgin Records Ltd.' then label4a= 'Virgin';
If label4= 'Virgin America' then label4a= 'Virgin';
If label4= 'VP Recrods' then label4a= 'VP Records';
If label4= 'Warlock Reocrds' then label4a= 'Warlock Records';
If label4= 'Sup Pup' then label4a= 'Sup Pop';
If label4= 'A1' then label4a= 'A1 Recordings';
If label4= 'BMG Eurodisc' then label4a= 'Arista Records';
If (label4= 'WARNER Music Benelux' & NewArtist='Macklemore') then label4a= 'Macklemore, LLC';
If (label4= 'WARNER Music Benelux' & NewArtist='Bob') then label4a= 'Atlantic Records';	
If (label4= 'Warner Dance Labels' & NewArtist='Bob') then label4a= 'Atlantic Records';	
If (label4= 'Warner Dance Labels' & NewArtist='Flo rida') then label4a= 'Atlantic Records';	
If label4= 'Terror Squad' then label4a= 'Terror Squad Entertainment';
If label4= 'Terror Squad Production' then label4a= 'Terror Squad Entertainment';
If label4= 'Bertelsmann Music Group' then label4a= 'BMG';
If label4= 'Big Life' then label4a= 'Tommy Boy';
If label4= 'Big Yard Music Group Ltd.' then label4a= 'MCA Records';
If label4= 'Bilawn Records' then label4a= 'Rhyme $yndicate Records';
If label4= 'Brainstorm Entertainment' then label4a= 'Brainstorm Enterprise';
If label4= 'Bystorm Entertainment' then label4a= 'Universal';
If label4= 'Violator' then label4a= 'Violator Records';
If label4= 'TVT Europe' then label4a= 'TVT Records';
If label4= 'Top Dawg' then label4a= 'Top Dawg Entertainment';
If label4= 'Thugged Out Entertainment' then label4a= 'Thugged Out Militainment';
If label4= 'Cheetah Recrods' then label4a= 'Cheetah Records';
If label4= 'CMG' then label4a= 'So So Def';
If label4= 'Col' then label4a= 'Cold Chillin';
If label4= 'ColliPark Music' then label4a= 'Collipark Records';
If label4= 'Deh Tyme Entertainment, Inc.' then label4a= 'Deh Tyme Entertainment';
If label4= 'Def Jam Classics' then label4a= 'Def Jam Recordings';
If label4= 'X-Mix' then label4a= 'Island Def Jam Music Group';
If label4= 'UNDEAS Recordings' then label4a= 'Undeas Recording';
If label4= 'Ultimix' then label4a= 'Violator Records';
If label4= 'Maybach Music' then label4a= 'Maybach Music Group';
If label4= 'Mega Records' then label4a= 'Tommy Boy';
If label4= 'Soundtable' then label4a= 'Giant Records';
If label4= 'Stampa Alternativa' then label4a= 'Chrysalis';
If label4= 'Sick Wild’ It Records' then label4a= 'Sick Wid It Records';
If label4= 'SBK' then label4a= 'SBK Records';
If label4= 'Noiseland' then label4a= 'Macklemore, LLC';
If label4= 'Northwestide Records' then label4a= 'Roc-A-Fella Records';
If label4= "October's Very Own" then label4a= 'Young Money Entertainment';
If label4= 'P.R.O. Division' then label4a= 'Rush Associated Labels';
If label4= 'Paisley Park' then label4a= 'Warner Bros. Records';
If label4= 'Warner Bros' then label4a= 'Warner Bros. Records';
If label4= 'Hustle' then label4a= 'Grand Hustle';
If label4= 'Hustle Entertainment' then label4a= 'Grand Hustle';
If label4= 'Hustle Gang' then label4a= 'Grand Hustle';
If label4= 'Studio 2000' then label4a= 'VP Records';
If label4= 'Skywalker Records' then label4a= 'Luke Records';
If label4= 'Skyywalker Records' then label4a= 'Luke Records';
If label4= 'Luke Skywalker Records' then label4a= 'Luke Records';
If label4= 'Getting Out Our Dreams' then label4a= 'G.O.O.D Music';
If label4= 'GMG' then label4a= 'Get Money Gang Entertainment';
If label4= 'Polystar (3)' then label4a= 'Island Def Jam Music Group';
If label4= 'Mergela Records' then label4a= 'Interscope Records';
If label4= 'Mighty Mouse' then label4a= 'Mighty Music';
If label4= 'Monami Entertainment' then label4a= 'Atlantic Records';
If label4= 'ISBA' then label4a= 'Tommy Boy';
If label4= 'Konlive' then label4a= 'Geffen Records';
If label4= 'Lexington' then label4a= 'Rush Associated Labels';
If label4= 'JSRC' then label4a= 'Diamond Style Records';
If label4= 'Poe Boy Music' then label4a= 'Poe Boy Entertainment';
If label4= "Cold Chillin'" then label4a= "Cold Chillin";
If label4= 'La Face Records' then label4a= 'LaFace Records';

if label4= 'Dup' then label4a= '';

If MAINARTIST= '@iHeartMemphis' then MainArtist= 'iHeartMemphis';
If ARTISTS= '@iHeartMemphis' then Artists= 'iHeartMemphis';
If ARTISTS= 'iHeartMemphis' then Artists= 'iheartmemphis';

*Fix Hit the Quan;
if songid=700 then label1a='Palm Tree';
if songid=700 then label2a='Rush Hour';
if songid=700 then newartist='iheartmemphis';
if songid=705 then newartist='iheartmemphis';
if songid='700' then songid='1';
if songid='705' then songid='1';

if songid ne '';

run;
proc sort data=songs; by label1a; run;
data majors; set music.majors;
if (independent_status=. & level=5) then independent_status=0;
if (independent_status=. & level=4) then independent_status=1;
if (independent_status=0 & level=4) then independent_status=1;
if (independent_status=. & level=3) then independent_status=0;
if (independent_status=. & level=2) then independent_status=0;
if (independent_status=. & level=1) then independent_status=0;

Y89="1989";
if (Y1989="N/A" OR Y1989="UK") then Y89=.;
Y90="1990";
if (Y1990="N/A" OR Y1990="UK") then Y90=.;
Y91="1991";
if (Y1991="N/A" OR Y1991="UK") then Y91=.;
Y92="1992";
if (Y1992="N/A" OR Y1992="UK") then Y92=.;
Y93="1993";
if (Y1993="N/A" OR Y1993="UK") then Y93=.;
Y94="1994";
if (Y1994="N/A" OR Y1994="UK") then Y94=.;
Y95="1995";
if (Y1995="N/A" OR Y1995="UK") then Y95=.;
Y96="1996";
if (Y1996="N/A" OR Y1996="UK") then Y96=.;
Y97="1997";
if (Y1997="N/A" OR Y1997="UK") then Y97=.;
Y98="1998";
if (Y1998="N/A" OR Y1998="UK") then Y98=.;
Y99="1999";
if (Y1999="N/A" OR Y1999="UK") then Y99=.;
Y00="2000";
if (Y2000="N/A" OR Y2000="UK") then Y00=.;
Y01="2001";
if (Y2001="N/A" OR Y2001="UK") then Y01=.;
Y02="2002";
if (Y2002="N/A" OR Y2002="UK") then Y02=.;
Y03="2003";
if (Y2003="N/A" OR Y2003="UK") then Y03=.;
Y04="2004";
if (Y2004="N/A" OR Y2004="UK") then Y04=.;
Y05="2005";
if (Y2005="N/A" OR Y2005="UK") then Y05=.;
Y06="2006";
if (Y2006="N/A" OR Y2006="UK") then Y06=.;
Y07="2007";
if (Y2007="N/A" OR Y2007="UK") then Y07=.;
Y08="2008";
if (Y2008="N/A" OR Y2008="UK") then Y08=.;
Y09="2009";
if (Y2009="N/A" OR Y2009="UK") then Y09=.;
Y10="2010";
if (Y2010="N/A" OR Y2010="UK") then Y10=.;
Y11="2011";
if (Y2011="N/A" OR Y2011="UK") then Y11=.;
Y12="2012";
if (Y2012="N/A" OR Y2012="UK") then Y12=.;
Y13="2013";
if (Y2013="N/A" OR Y2013="UK") then Y13=.;
Y14="2014";
if (Y2014="N/A" OR Y2014="UK") then Y14=.;
Y15="2015";
if (Y2015="N/A" OR Y2015="UK") then Y15=.;

labels=labels;
If labels= 'Arista' then labels= 'Arista Records';
If labels= 'Atlantic' then labels= 'Atlantic Records';
If labels= 'Atlantic Recording Corporation' then labels= 'Atlantic Records';
If labels= 'Bad Boy Entertainment' then labels= 'Bad Boy Records';
If labels= 'Blunt Recordings' then labels= 'Blunt Records';
If labels= 'Capitol Records, LLC' then labels= 'Capitol Records';
If labels= 'Columbia' then labels= 'Columbia Records';
If labels= 'Def Jam Recordings Group Inc.' then labels= 'Def Jam Recordings';
If labels= 'Def Jam Music Group' then labels= 'Def Jam Recordings';
If labels= 'EastWest Records America' then labels= 'EastWest';
If labels= 'EastWest Recrods America' then labels= 'EastWest';
If labels= 'Elektra' then labels= 'Elektra Records';
If labels= 'G.O.O.D. MUSIC' then labels= 'G.O.O.D Music';
If labels= 'How You Love That' then labels= 'How You Love That Records';
If labels= 'Island Black Music' then labels= 'Island';
If labels= 'Island Records' then labels= 'Island';
If labels= 'Island Records Group' then labels= 'Island';
If labels= 'Penalty Recordings' then labels= 'Penalty Records';
If labels= 'PWL America Records Ltd.' then labels= 'PWL America Records Ltd';
If labels= 'RCA' then labels= 'RCA Records';
If labels= 'Roc Nation LLC' then labels= 'Roc Nation';
If labels= 'Rostrum Recrods' then labels= 'Rostrum Records';
If labels= 'Star Trek Entertainment' then labels= 'Star Trak Entertainment';
If labels= 'Universal Motown' then labels= 'Motown';
If labels= 'Universal Motown Records' then labels= 'Motown';
If labels= 'Universal Motwon' then labels= 'Motown';
If labels= 'Universal Republic' then labels= 'Republic Records';
If labels= 'Universal Records' then labels= 'Universal';
If labels= 'Universal Recrods' then labels= 'Universal';
If labels= 'Universal Music' then labels= 'Universal';
If labels= 'Universal Music B.V.' then labels= 'Universal';
If labels= 'Universal Music Operations Ltd.' then labels= 'Universal';
If labels= 'Virgin Records America, Inc.' then labels= 'Virgin';
If labels= 'Virgin Records Ltd.' then labels= 'Virgin';
If labels= 'Virgin America' then labels= 'Virgin';
If labels= 'VP Recrods' then labels= 'VP Records';
If labels= 'Warlock Reocrds' then labels= 'Warlock Records';
If labels= 'Sup Pup' then labels= 'Sup Pop';
If labels= 'A1' then labels= 'A1 Recordings';
If labels= 'BMG Eurodisc' then labels= 'Arista Records';
If (labels= 'WARNER Music Benelux' & NewArtist='Macklemore') then labels= 'Macklemore, LLC';
If (labels= 'WARNER Music Benelux' & NewArtist='Bob') then labels= 'Atlantic Records';	
If (labels= 'Warner Dance Labels' & NewArtist='Bob') then labels= 'Atlantic Records';	
If (labels= 'Warner Dance Labels' & NewArtist='Flo rida') then labels= 'Atlantic Records';		
If labels= 'Terror Squad' then labels= 'Terror Squad Entertainment';
If labels= 'Terror Squad Production' then labels= 'Terror Squad Entertainment';
If labels= 'Bertelsmann Music Group' then labels= 'BMG';
If labels= 'Big Life' then labels= 'Tommy Boy';
If labels= 'Big Yard Music Group Ltd.' then labels= 'MCA Records';
If labels= 'Bilawn Records' then labels= 'Rhyme $yndicate Records';
If labels= 'Brainstorm Entertainment' then labels= 'Brainstorm Enterprise';
If labels= 'Bystorm Entertainment' then labels= 'Universal';
If labels= 'Violator' then labels= 'Violator Records';
If labels= 'TVT Europe' then labels= 'TVT Records';
If labels= 'Top Dawg' then labels= 'Top Dawg Entertainment';
If labels= 'Thugged Out Entertainment' then labels= 'Thugged Out Militainment';
If labels= 'Cheetah Recrods' then labels= 'Cheetah Records';
If labels= 'CMG' then labels= 'So So Def';
If labels= 'Col' then labels= 'Cold Chillin';
If labels= 'ColliPark Music' then labels= 'Collipark Records';
If labels= 'Deh Tyme Entertainment, Inc.' then labels= 'Deh Tyme Entertainment';
If labels= 'Def Jam Classics' then labels= 'Def Jam Recordings';
If labels= 'X-Mix' then labels= 'Island Def Jam Music Group';
If labels= 'UNDEAS Recordings' then labels= 'Undeas Recording';
If labels= 'Ultimix' then labels= 'Violator Records';
If labels= 'Maybach Music' then labels= 'Maybach Music Group';
If labels= 'Mega Records' then labels= 'Tommy Boy';
If labels= 'Soundtable' then labels= 'Giant Records';
If labels= 'Stampa Alternativa' then labels= 'Chrysalis';
If labels= 'Sick Wild’ It Records' then labels= 'Sick Wid It Records';
If labels= 'SBK' then labels= 'SBK Records';
If labels= 'Noiseland' then labels= 'Macklemore, LLC';
If labels= 'Northwestide Records' then labels= 'Roc-A-Fella Records';
If labels= "October's Very Own" then labels= 'Young Money Entertainment';
If labels= 'P.R.O. Division' then labels= 'Rush Associated Labels';
If labels= 'Paisley Park' then labels= 'Warner Bros. Records';
If labels= 'Warner Bros' then labels= 'Warner Bros. Records';
If labels= 'Hustle' then labels= 'Grand Hustle';
If labels= 'Hustle Entertainment' then labels= 'Grand Hustle';
If labels= 'Hustle Gang' then labels= 'Grand Hustle';
If labels= 'Studio 2000' then labels= 'VP Records';
If labels= 'Skywalker Records' then labels= 'Luke Records';
If labels= 'Skyywalker Records' then labels= 'Luke Records';
If labels= 'Luke Skywalker Records' then labels= 'Luke Records';
If labels= 'Getting Out Our Dreams' then labels= 'G.O.O.D Music';
If labels= 'GMG' then labels= 'Get Money Gang Entertainment';
If labels= 'Polystar (3)' then labels= 'Island Def Jam Music Group';
If labels= 'Mergela Records' then labels= 'Interscope Records';
If labels= 'Mighty Mouse' then labels= 'Mighty Music';
If labels= 'Monami Entertainment' then labels= 'Atlantic Records';
If labels= 'ISBA' then labels= 'Tommy Boy';
If labels= 'Konlive' then labels= 'Geffen Records';
If labels= 'Lexington' then labels= 'Rush Associated Labels';
If labels= 'JSRC' then labels= 'Diamond Style Records';
If labels= 'Poe Boy Music' then labels= 'Poe Boy Entertainment';
If labels= "Cold Chillin'" then labels= 'Cold Chillin';
If labels= 'La Face Records' then labels= 'LaFace Records';

run;


proc sort data=majors; by labels;
data y89l(keep=labels distribution independent_status level y89) y90l(keep=labels distribution independent_status level y90)
y91l(keep=labels distribution independent_status level y91) y92l(keep=labels distribution independent_status level y92)
y93l(keep=labels distribution independent_status level y93) y94l(keep=labels distribution independent_status level y94)
y95l(keep=labels distribution independent_status level y95) y96l(keep=labels distribution independent_status level y96) 
y97l(keep=labels distribution independent_status level y97) y98l(keep=labels distribution independent_status level y98)
y99l(keep=labels distribution independent_status level y99) y00l(keep=labels distribution independent_status level y00)
y01l(keep=labels distribution independent_status level y01) y02l(keep=labels distribution independent_status level y02)
y03l(keep=labels distribution independent_status level y03) y04l(keep=labels distribution independent_status level y04)
y05l(keep=labels distribution independent_status level y05) y06l(keep=labels distribution independent_status level y06)
y07l(keep=labels distribution independent_status level y07) y08l(keep=labels distribution independent_status level y08)
y09l(keep=labels distribution independent_status level y09) y10l(keep=labels distribution independent_status level y10)
y11l(keep=labels distribution independent_status level y11) y12l(keep=labels distribution independent_status level y12)
y13l(keep=labels distribution independent_status level y13) y14l(keep=labels distribution independent_status level y14)
y15l(keep=labels distribution independent_status level y15); set majors;

if y89=1989 then output y89l; if y90=1990 then output y90l;
if y91=1991 then output y91l; if y92=1992 then output y92l;
if y93=1993 then output y93l; if y94=1994 then output y94l;
if y95=1995 then output y95l; if y96=1996 then output y96l;
if y97=1997 then output y97l; if y98=1998 then output y98l;
if y99=1999 then output y99l; if y00=2000 then output y00l;
if y01=2001 then output y01l; if y02=2002 then output y02l;
if y03=2003 then output y03l; if y04=2004 then output y04l;
if y05=2005 then output y05l; if y06=2006 then output y06l;
if y07=2007 then output y07l; if y08=2008 then output y08l;
if y09=2009 then output y09l; if y10=2010 then output y10l;
if y11=2011 then output y11l; if y12=2012 then output y12l;
if y13=2013 then output y13l; if y14=2014 then output y14l;
if y15=2015 then output y15l;
run;
data y89s y90s y91s y92s y93s y94s y95s y96s y97s y98s
y99s y00s y01s y02s y03s y04s y05s y06s y07s y08s
y09s y10s y11s y12s y13s y14s y15s; set songs;

if year=1989 then output y89s; if year=1990 then output y90s;
if year=1991 then output y91s; if year=1992 then output y92s;
if year=1993 then output y93s; if year=1994 then output y94s;
if year=1995 then output y95s; if year=1996 then output y96s;
if year=1997 then output y97s; if year=1998 then output y98s;
if year=1999 then output y99s; if year=2000 then output y00s;
if year=2001 then output y01s; if year=2002 then output y02s;
if year=2003 then output y03s; if year=2004 then output y04s;
if year=2005 then output y05s; if year=2006 then output y06s;
if year=2007 then output y07s; if year=2008 then output y08s;
if year=2009 then output y09s; if year=2010 then output y10s;
if year=2011 then output y11s; if year=2012 then output y12s;
if year=2013 then output y13s; if year=2014 then output y14s;
if year=2015 then output y15s;

drop label1 label2 label3 label4;
run;


*Create Yearly Merges for each Label 1, 2, 3, & 4;
proc sort data=y89s; by label1a;
data f89(rename=(labels=label1)); merge y89s(rename=(label1a=labels)) y89l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y89;
if rank ne .;
by labels;
run;
proc sort data=f89; by label2a;
data f89(rename=(labels=label2)); merge f89(rename=(label2a=labels)) y89l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y89;
if rank ne .;
by labels;
run;
proc sort data=f89; by label3a;
data f89(rename=(labels=label3)); merge f89(rename=(label3a=labels)) y89l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y89;
if rank ne .;
by labels;
run;
proc sort data=f89; by label4a;
data f89(rename=(labels=label4)); merge f89(rename=(label4a=labels)) y89l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y89;
if rank ne .;
by labels;
run;

proc sort data=y90s; by label1a;
data f90(rename=(labels=label1)); merge y90s(rename=(label1a=labels)) y90l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y90;
if rank ne .;
by labels;
run;
proc sort data=f90; by label2a;
data f90(rename=(labels=label2)); merge f90(rename=(label2a=labels)) y90l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y90;
if rank ne .;
by labels;
run;
proc sort data=f90; by label3a;
data f90(rename=(labels=label3)); merge f90(rename=(label3a=labels)) y90l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y90;
if rank ne .;
by labels;
run;
proc sort data=f90; by label4a;
data f90(rename=(labels=label4)); merge f90(rename=(label4a=labels)) y90l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y90;
if rank ne .;
by labels;
run;

proc sort data=y91s; by label1a;
data f91(rename=(labels=label1)); merge y91s(rename=(label1a=labels)) y91l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y91;
if rank ne .;
by labels;
run;
proc sort data=f91; by label2a;
data f91(rename=(labels=label2)); merge f91(rename=(label2a=labels)) y91l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y91;
if rank ne .;
by labels;
run;
proc sort data=f91; by label3a;
data f91(rename=(labels=label3)); merge f91(rename=(label3a=labels)) y91l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y91;
if rank ne .;
by labels;
run;
proc sort data=f91; by label4a;
data f91(rename=(labels=label4)); merge f91(rename=(label4a=labels)) y91l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y91;
if rank ne .;
by labels;
run;

proc sort data=y92s; by label1a;
data f92(rename=(labels=label1)); merge y92s(rename=(label1a=labels)) y92l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y92;
if rank ne .;
by labels;
run;
proc sort data=f92; by label2a;
data f92(rename=(labels=label2)); merge f92(rename=(label2a=labels)) y92l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y92;
if rank ne .;
by labels;
run;
proc sort data=f92; by label3a;
data f92(rename=(labels=label3)); merge f92(rename=(label3a=labels)) y92l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y92;
if rank ne .;
by labels;
run;
proc sort data=f92; by label4a;
data f92(rename=(labels=label4)); merge f92(rename=(label4a=labels)) y92l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y92;
if rank ne .;
by labels;
run;

proc sort data=y93s; by label1a;
data f93(rename=(labels=label1)); merge y93s(rename=(label1a=labels)) y93l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y93;
if rank ne .;
by labels;
run;
proc sort data=f93; by label2a;
data f93(rename=(labels=label2)); merge f93(rename=(label2a=labels)) y93l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y93;
if rank ne .;
by labels;
run;
proc sort data=f93; by label3a;
data f93(rename=(labels=label3)); merge f93(rename=(label3a=labels)) y93l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y93;
if rank ne .;
by labels;
run;
proc sort data=f93; by label4a;
data f93(rename=(labels=label4)); merge f93(rename=(label4a=labels)) y93l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y93;
if rank ne .;
by labels;
run;

proc sort data=y94s; by label1a;
data f94(rename=(labels=label1)); merge y94s(rename=(label1a=labels)) y94l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y94;
if rank ne .;
by labels;
run;
proc sort data=f94; by label2a;
data f94(rename=(labels=label2)); merge f94(rename=(label2a=labels)) y94l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y94;
if rank ne .;
by labels;
run;
proc sort data=f94; by label3a;
data f94(rename=(labels=label3)); merge f94(rename=(label3a=labels)) y94l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y94;
if rank ne .;
by labels;
run;
proc sort data=f94; by label4a;
data f94(rename=(labels=label4)); merge f94(rename=(label4a=labels)) y94l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y94;
if rank ne .;
by labels;
run;

proc sort data=y95s; by label1a;
data f95(rename=(labels=label1)); merge y95s(rename=(label1a=labels)) y95l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y95;
if rank ne .;
by labels;
run;
proc sort data=f95; by label2a;
data f95(rename=(labels=label2)); merge f95(rename=(label2a=labels)) y95l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y95;
if rank ne .;
by labels;
run;
proc sort data=f95; by label3a;
data f95(rename=(labels=label3)); merge f95(rename=(label3a=labels)) y95l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y95;
if rank ne .;
by labels;
run;
proc sort data=f95; by label4a;
data f95(rename=(labels=label4)); merge f95(rename=(label4a=labels)) y95l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y95;
if rank ne .;
by labels;
run;

proc sort data=y96s; by label1a;
data f96(rename=(labels=label1)); merge y96s(rename=(label1a=labels)) y96l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y96;
if rank ne .;
by labels;
run;
proc sort data=f96; by label2a;
data f96(rename=(labels=label2)); merge f96(rename=(label2a=labels)) y96l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y96;
if rank ne .;
by labels;
run;
proc sort data=f96; by label3a;
data f96(rename=(labels=label3)); merge f96(rename=(label3a=labels)) y96l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y96;
if rank ne .;
by labels;
run;
proc sort data=f96; by label4a;
data f96(rename=(labels=label4)); merge f96(rename=(label4a=labels)) y96l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y96;
if rank ne .;
by labels;
run;

proc sort data=y97s; by label1a;
data f97(rename=(labels=label1)); merge y97s(rename=(label1a=labels)) y97l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y97;
if rank ne .;
by labels;
run;
proc sort data=f97; by label2a;
data f97(rename=(labels=label2)); merge f97(rename=(label2a=labels)) y97l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y97;
if rank ne .;
by labels;
run;
proc sort data=f97; by label3a;
data f97(rename=(labels=label3)); merge f97(rename=(label3a=labels)) y97l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y97;
if rank ne .;
by labels;
run;
proc sort data=f97; by label4a;
data f97(rename=(labels=label4)); merge f97(rename=(label4a=labels)) y97l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y97;
if rank ne .;
by labels;
run;

proc sort data=y98s; by label1a;
data f98(rename=(labels=label1)); merge y98s(rename=(label1a=labels)) y98l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y98;
if rank ne .;
by labels;
run;
proc sort data=f98; by label2a;
data f98(rename=(labels=label2)); merge f98(rename=(label2a=labels)) y98l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y98;
if rank ne .;
by labels;
run;
proc sort data=f98; by label3a;
data f98(rename=(labels=label3)); merge f98(rename=(label3a=labels)) y98l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y98;
if rank ne .;
by labels;
run;
proc sort data=f98; by label4a;
data f98(rename=(labels=label4)); merge f98(rename=(label4a=labels)) y98l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y98;
if rank ne .;
by labels;
run;

proc sort data=y99s; by label1a;
data f99(rename=(labels=label1)); merge y99s(rename=(label1a=labels)) y99l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y99;
if rank ne .;
by labels;
run;
proc sort data=f99; by label2a;
data f99(rename=(labels=label2)); merge f99(rename=(label2a=labels)) y99l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y99;
if rank ne .;
by labels;
run;
proc sort data=f99; by label3a;
data f99(rename=(labels=label3)); merge f99(rename=(label3a=labels)) y99l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y99;
if rank ne .;
by labels;
run;
proc sort data=f99; by label4a;
data f99(rename=(labels=label4)); merge f99(rename=(label4a=labels)) y99l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y99;
if rank ne .;
by labels;
run;

proc sort data=y00s; by label1a;
data f00(rename=(labels=label1)); merge y00s(rename=(label1a=labels)) y00l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y00;
if rank ne .;
by labels;
run;
proc sort data=f00; by label2a;
data f00(rename=(labels=label2)); merge f00(rename=(label2a=labels)) y00l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y00;
if rank ne .;
by labels;
run;
proc sort data=f00; by label3a;
data f00(rename=(labels=label3)); merge f00(rename=(label3a=labels)) y00l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y00;
if rank ne .;
by labels;
run;
proc sort data=f00; by label4a;
data f00(rename=(labels=label4)); merge f00(rename=(label4a=labels)) y00l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y00;
if rank ne .;
by labels;
run;

proc sort data=y01s; by label1a;
data f01(rename=(labels=label1)); merge y01s(rename=(label1a=labels)) y01l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y01;
if rank ne .;
by labels;
run;
proc sort data=f01; by label2a;
data f01(rename=(labels=label2)); merge f01(rename=(label2a=labels)) y01l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y01;
if rank ne .;
by labels;
run;
proc sort data=f01; by label3a;
data f01(rename=(labels=label3)); merge f01(rename=(label3a=labels)) y01l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y01;
if rank ne .;
by labels;
run;
proc sort data=f01; by label4a;
data f01(rename=(labels=label4)); merge f01(rename=(label4a=labels)) y01l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y01;
if rank ne .;
by labels;
run;

proc sort data=y02s; by label1a;
data f02(rename=(labels=label1)); merge y02s(rename=(label1a=labels)) y02l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y02;
if rank ne .;
by labels;
run;
proc sort data=f02; by label2a;
data f02(rename=(labels=label2)); merge f02(rename=(label2a=labels)) y02l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y02;
if rank ne .;
by labels;
run;
proc sort data=f02; by label3a;
data f02(rename=(labels=label3)); merge f02(rename=(label3a=labels)) y02l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y02;
if rank ne .;
by labels;
run;
proc sort data=f02; by label4a;
data f02(rename=(labels=label4)); merge f02(rename=(label4a=labels)) y02l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y02;
if rank ne .;
by labels;
run;

proc sort data=y03s; by label1a;
data f03(rename=(labels=label1)); merge y03s(rename=(label1a=labels)) y03l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y03;
if rank ne .;
by labels;
run;
proc sort data=f03; by label2a;
data f03(rename=(labels=label2)); merge f03(rename=(label2a=labels)) y03l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y03;
if rank ne .;
by labels;
run;
proc sort data=f03; by label3a;
data f03(rename=(labels=label3)); merge f03(rename=(label3a=labels)) y03l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y03;
if rank ne .;
by labels;
run;
proc sort data=f03; by label4a;
data f03(rename=(labels=label4)); merge f03(rename=(label4a=labels)) y03l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y03;
if rank ne .;
by labels;
run;

proc sort data=y04s; by label1a;
data f04(rename=(labels=label1)); merge y04s(rename=(label1a=labels)) y04l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y04;
if rank ne .;
by labels;
run;
proc sort data=f04; by label2a;
data f04(rename=(labels=label2)); merge f04(rename=(label2a=labels)) y04l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y04;
if rank ne .;
by labels;
run;
proc sort data=f04; by label3a;
data f04(rename=(labels=label3)); merge f04(rename=(label3a=labels)) y04l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y04;
if rank ne .;
by labels;
run;
proc sort data=f04; by label4a;
data f04(rename=(labels=label4)); merge f04(rename=(label4a=labels)) y04l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y04;
if rank ne .;
by labels;
run;

proc sort data=y05s; by label1a;
data f05(rename=(labels=label1)); merge y05s(rename=(label1a=labels)) y05l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y05;
if rank ne .;
by labels;
run;
proc sort data=f05; by label2a;
data f05(rename=(labels=label2)); merge f05(rename=(label2a=labels)) y05l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y05;
if rank ne .;
by labels;
run;
proc sort data=f05; by label3a;
data f05(rename=(labels=label3)); merge f05(rename=(label3a=labels)) y05l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y05;
if rank ne .;
by labels;
run;
proc sort data=f05; by label4a;
data f05(rename=(labels=label4)); merge f05(rename=(label4a=labels)) y05l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y05;
if rank ne .;
by labels;
run;

proc sort data=y06s; by label1a;
data f06(rename=(labels=label1)); merge y06s(rename=(label1a=labels)) y06l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y06;
if rank ne .;
by labels;
run;
proc sort data=f06; by label2a;
data f06(rename=(labels=label2)); merge f06(rename=(label2a=labels)) y06l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y06;
if rank ne .;
by labels;
run;
proc sort data=f06; by label3a;
data f06(rename=(labels=label3)); merge f06(rename=(label3a=labels)) y06l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y06;
if rank ne .;
by labels;
run;
proc sort data=f06; by label4a;
data f06(rename=(labels=label4)); merge f06(rename=(label4a=labels)) y06l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y06;
if rank ne .;
by labels;
run;

proc sort data=y07s; by label1a;
data f07(rename=(labels=label1)); merge y07s(rename=(label1a=labels)) y07l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y07;
if rank ne .;
by labels;
run;
proc sort data=f07; by label2a;
data f07(rename=(labels=label2)); merge f07(rename=(label2a=labels)) y07l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y07;
if rank ne .;
by labels;
run;
proc sort data=f07; by label3a;
data f07(rename=(labels=label3)); merge f07(rename=(label3a=labels)) y07l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y07;
if rank ne .;
by labels;
run;
proc sort data=f07; by label4a;
data f07(rename=(labels=label4)); merge f07(rename=(label4a=labels)) y07l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y07;
if rank ne .;
by labels;
run;

proc sort data=y08s; by label1a;
data f08(rename=(labels=label1)); merge y08s(rename=(label1a=labels)) y08l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y08;
if rank ne .;
by labels;
run;
proc sort data=f08; by label2a;
data f08(rename=(labels=label2)); merge f08(rename=(label2a=labels)) y08l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y08;
if rank ne .;
by labels;
run;
proc sort data=f08; by label3a;
data f08(rename=(labels=label3)); merge f08(rename=(label3a=labels)) y08l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y08;
if rank ne .;
by labels;
run;
proc sort data=f08; by label4a;
data f08(rename=(labels=label4)); merge f08(rename=(label4a=labels)) y08l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y08;
if rank ne .;
by labels;
run;

proc sort data=y09s; by label1a;
data f09(rename=(labels=label1)); merge y09s(rename=(label1a=labels)) y09l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y09;
if rank ne .;
by labels;
run;
proc sort data=f09; by label2a;
data f09(rename=(labels=label2)); merge f09(rename=(label2a=labels)) y09l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y09;
if rank ne .;
by labels;
run;
proc sort data=f09; by label3a;
data f09(rename=(labels=label3)); merge f09(rename=(label3a=labels)) y09l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y09;
if rank ne .;
by labels;
run;
proc sort data=f09; by label4a;
data f09(rename=(labels=label4)); merge f09(rename=(label4a=labels)) y09l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y09;
if rank ne .;
by labels;
run;

proc sort data=y10s; by label1a;
data f10(rename=(labels=label1)); merge y10s(rename=(label1a=labels)) y10l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y10;
if rank ne .;
by labels;
run;
proc sort data=f10; by label2a;
data f10(rename=(labels=label2)); merge f10(rename=(label2a=labels)) y10l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y10;
if rank ne .;
by labels;
run;
proc sort data=f10; by label3a;
data f10(rename=(labels=label3)); merge f10(rename=(label3a=labels)) y10l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y10;
if rank ne .;
by labels;
run;
proc sort data=f10; by label4a;
data f10(rename=(labels=label4)); merge f10(rename=(label4a=labels)) y10l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y10;
if rank ne .;
by labels;
run;

proc sort data=y11s; by label1a;
data f11(rename=(labels=label1)); merge y11s(rename=(label1a=labels)) y11l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y11;
if rank ne .;
by labels;
run;
proc sort data=f11; by label2a;
data f11(rename=(labels=label2)); merge f11(rename=(label2a=labels)) y11l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y11;
if rank ne .;
by labels;
run;
proc sort data=f11; by label3a;
data f11(rename=(labels=label3)); merge f11(rename=(label3a=labels)) y11l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y11;
if rank ne .;
by labels;
run;
proc sort data=f11; by label4a;
data f11(rename=(labels=label4)); merge f11(rename=(label4a=labels)) y11l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y11;
if rank ne .;
by labels;
run;

proc sort data=y12s; by label1a;
data f12(rename=(labels=label1)); merge y12s(rename=(label1a=labels)) y12l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y12;
if rank ne .;
by labels;
run;
proc sort data=f12; by label2a;
data f12(rename=(labels=label2)); merge f12(rename=(label2a=labels)) y12l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y12;
if rank ne .;
by labels;
run;
proc sort data=f12; by label3a;
data f12(rename=(labels=label3)); merge f12(rename=(label3a=labels)) y12l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y12;
if rank ne .;
by labels;
run;
proc sort data=f12; by label4a;
data f12(rename=(labels=label4)); merge f12(rename=(label4a=labels)) y12l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y12;
if rank ne .;
by labels;
run;

proc sort data=y13s; by label1a;
data f13(rename=(labels=label1)); merge y13s(rename=(label1a=labels)) y13l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y13;
if rank ne .;
by labels;
run;
proc sort data=f13; by label2a;
data f13(rename=(labels=label2)); merge f13(rename=(label2a=labels)) y13l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y13;
if rank ne .;
by labels;
run;
proc sort data=f13; by label3a;
data f13(rename=(labels=label3)); merge f13(rename=(label3a=labels)) y13l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y13;
if rank ne .;
by labels;
run;
proc sort data=f13; by label4a;
data f13(rename=(labels=label4)); merge f13(rename=(label4a=labels)) y13l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y13;
if rank ne .;
by labels;
run;

proc sort data=y14s; by label1a;
data f14(rename=(labels=label1)); merge y14s(rename=(label1a=labels)) y14l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y14;
if rank ne .;
by labels;
run;
proc sort data=f14; by label2a;
data f14(rename=(labels=label2)); merge f14(rename=(label2a=labels)) y14l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y14;
if rank ne .;
by labels;
run;
proc sort data=f14; by label3a;
data f14(rename=(labels=label3)); merge f14(rename=(label3a=labels)) y14l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y14;
if rank ne .;
by labels;
run;
proc sort data=f14; by label4a;
data f14(rename=(labels=label4)); merge f14(rename=(label4a=labels)) y14l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y14;
if rank ne .;
by labels;
run;

proc sort data=y15s; by label1a;
data f15(rename=(labels=label1)); merge y15s(rename=(label1a=labels)) y15l ;
rename independent_status=Ind1;
rename Level=Lvl1;
rename distribution=Distr1;
drop y15;
if rank ne .;
by labels;
run;
proc sort data=f15; by label2a;
data f15(rename=(labels=label2)); merge f15(rename=(label2a=labels)) y15l;
rename independent_status=Ind2;
rename Level=Lvl2;
drop distribution y15;
if rank ne .;
by labels;
run;
proc sort data=f15; by label3a;
data f15(rename=(labels=label3)); merge f15(rename=(label3a=labels)) y15l;
rename independent_status=Ind3;
rename Level=Lvl3;
drop distribution y15;
if rank ne .;
by labels;
run;
proc sort data=f15; by label4a;
data f15(rename=(labels=label4)); merge f15(rename=(label4a=labels)) y15l;
rename independent_status=Ind4;
rename Level=Lvl4;
drop distribution y15;
if rank ne .;
by labels;
run;


****************FINAL DATASET OF ALL SONGS AND LABEL LEVELS *********;
data music.allsongs; set f89 f90 f91 f92
f93 f94 f95 f96 f97 f98 f99 f00 f01 f02
f03 f04 f05 f06 f07 f08 f09 f10 f11 f12
f13 f14 f15; run;


PROC IMPORT OUT= MUSIC.Religion 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\Religion.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.religion; by songid; run;

PROC IMPORT OUT= MUSIC.MP 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\Material Possessions.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.MP; by songid; run;

PROC IMPORT OUT= MUSIC.Pro 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\Profanity.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.pro; by songid; run;

PROC IMPORT OUT= MUSIC.ProN 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\Profanity - NWORD.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.pron; by songid; run;

PROC IMPORT OUT= MUSIC.ProS 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\Profane - S.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.pros; by songid; run;

PROC IMPORT OUT= MUSIC.wordct 
            DATAFILE= "C:\Users\Matthew\Dropbox\Papers\Cultural Tectonics\Data\Word Counts\WordCount.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
proc sort data=music.wordct out=wordct; by songid; run;

data allct; merge music.religion music.mp music.pro music.pron music.pros wordct;
array me relct materialct proct pronct prosct;
do over me;
if me=. then me=0;
end;

array we relcov materialcov procov proncov proscov;
do over we;
if we="" then we=0;
end;
drop artist_rel artist_mp artist_pro artist_pron artist_ct;
by songid; 
run;

data allsongs; set music.allsongs;
cc=(songid + 0);
dd=(Date *1);
ee=(Month *1);
drop songid Date Month;
rename cc=SongID;
rename dd=Date;
rename ee=Month;
run;
proc sort data=allct; by songid; run;
proc sort data=allsongs; by songid; run;
data music.allcalc; merge allsongs allct; by songid; 
if songid='700' then songid='1';
if songid='705' then songid='1';
if songid='1' then WeeksOn='9';
ff=(WeeksOn *1);
drop WeeksOn;
rename ff=WeeksOn;
run;
